logging:
  level:
    hu.progmasters: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
spring.http.encoding.charset: UTF-8
# Enable http encoding support.
spring.http.encoding.enabled: true
# Force the encoding to the configured charset on HTTP requests and responses.
spring.http.encoding.force: true

